[[redirects]]
  from = "/service-areas/st-catharines.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/niagara-falls.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/niagara-on-the-lake.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/welland.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/thorold.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/port-colborne.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/pelham.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/lincoln.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/grimsby.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/stoney-creek.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/hamilton.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/ancaster.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/burlington.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/oakville.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/mississauga.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/toronto.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/brampton.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/vaughan.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/newmarket.html"
  to = "/service-areas.html"
  status = 301

[[redirects]]
  from = "/service-areas/gta.html"
  to = "/service-areas.html"
  status = 301
